"""SIH Problem Statement 26187 — FIX #3: Suspicious-Activity Hypothesis Validation Test Suite.

Verifies:
A. Event #1 is independently created/generated.
B. Event #2 is independently created/generated.
C. Separate event/evidence records without field-stuffing.
D. Shared subject pseudonym context.
E. Hypothesis engine evaluates independent signals together.
F. Resulting hypothesis is specifically SUSPICIOUS_ACTIVITY.
G. Explanation identifies contributing independent signals without prohibited terms.
H. Negative control cases: single event does NOT produce SUSPICIOUS_ACTIVITY; different subjects do NOT produce it.
I. Clean separation: zero stuffing of unrelated fields into a single Evidence object.
"""

from __future__ import annotations

import tempfile
from pathlib import Path
import pytest

from gods_eye.events.event_store import SQLiteEventStore
from gods_eye.schemas.camera import Zone
from gods_eye.schemas.detection import BoundingBox
from gods_eye.schemas.environment import LightingCondition, SystemMode
from gods_eye.schemas.event import Event, EventType
from gods_eye.schemas.reasoning import Evidence
from gods_eye.situational.evaluator import SituationalRiskEvaluator
from gods_eye.situational.hypothesis import (
    PROHIBITED_TERMS,
    HypothesisGenerator,
)
from gods_eye.zones.dwell_engine import DwellEngine
from gods_eye.zones.fence_engine import FenceEngine
from gods_eye.zones.night_rules import NightMovementEngine


@pytest.fixture
def restricted_vault_zone() -> Zone:
    """Fixture providing a restricted vault zone configuration."""
    return Zone(
        zone_id="zone_vault",
        camera_id="cam-01",
        display_name="Vault Restricted Area",
        polygon=[(0.0, 0.0), (0.5, 0.0), (0.5, 0.5), (0.0, 0.5)],
        zone_type="restricted",
        expected_dwell_s=(0.0, 30.0),
    )


class TestIndependentEventGenerationAndSeparation:
    """Proves Requirements A, B, C, D, and I."""

    def test_independent_phase9_event_generation_and_storage(
        self, restricted_vault_zone: Zone
    ) -> None:
        """Requirement A & B & C: Generate two genuinely independent Phase 9 events."""
        with tempfile.TemporaryDirectory() as tmpdir:
            store = SQLiteEventStore(str(Path(tmpdir) / "events.db"))
            fence_engine = FenceEngine()
            dwell_engine = DwellEngine(default_max_dwell_s=30.0, default_std_dwell_s=10.0)

            subject_ref = "subject_alpha_99"
            t0_ns = 1_000_000_000

            # 1. Event #1: RESTRICTED_ZONE_INTRUSION independently generated by FenceEngine
            bbox = BoundingBox(x1=100, y1=100, x2=200, y2=200)
            fence_events = fence_engine.check_subject(
                subject_ref=subject_ref,
                bbox=bbox,
                camera_id="cam-01",
                timestamp_ns=t0_ns,
                source_resolution=(1000, 1000),
                zones=[restricted_vault_zone],
                confidence=0.95,
            )
            assert len(fence_events) == 1
            fence_ev = fence_events[0]
            assert fence_ev.event_type == "RESTRICTED_ZONE_INTRUSION"
            assert fence_ev.is_restricted_zone is True

            ev_record_1 = Event(
                event_id="ev_indep_fence_01",
                event_type=EventType.RESTRICTED_ZONE_INTRUSION,
                global_id=subject_ref,
                camera_id="cam-01",
                timestamp_ns=t0_ns,
                frame_id=10,
                confidence=0.95,
                explanation=fence_ev.explanation,
                zone_id="zone_vault",
                metadata=fence_engine.build_evidence_payload(fence_ev),
            )
            store.append(ev_record_1)

            # 2. Event #2: LOITERING_DETECTED independently generated by DwellEngine
            t1_ns = t0_ns + 100_000_000_000  # 100s later (exceeds 30s max dwell)
            dwell_engine.record_zone_presence(
                subject_ref=subject_ref,
                zone_id="zone_vault",
                camera_id="cam-01",
                timestamp_ns=t0_ns,
                confidence=0.92,
                zone=restricted_vault_zone,
            )
            dwell_ev = dwell_engine.record_zone_presence(
                subject_ref=subject_ref,
                zone_id="zone_vault",
                camera_id="cam-01",
                timestamp_ns=t1_ns,
                confidence=0.92,
                zone=restricted_vault_zone,
            )
            assert dwell_ev is not None
            assert dwell_ev.zone_dwell_sigma > 5.0

            ev_record_2 = Event(
                event_id="ev_indep_dwell_01",
                event_type=EventType.LOITERING_DETECTED,
                global_id=subject_ref,
                camera_id="cam-01",
                timestamp_ns=t1_ns,
                frame_id=3000,
                confidence=0.92,
                explanation=dwell_ev.explanation,
                zone_id="zone_vault",
                metadata=dwell_engine.build_evidence_payload(dwell_ev),
            )
            store.append(ev_record_2)

            # Verify in store: 2 distinct events with different event_ids and types
            queried = store.query_events()
            assert len(queried) == 2
            event_types = {e.event_type for e in queried}
            assert event_types == {
                EventType.RESTRICTED_ZONE_INTRUSION,
                EventType.LOITERING_DETECTED,
            }
            assert queried[0].event_id != queried[1].event_id

            store.close()

    def test_separate_evidence_records_no_field_stuffing(
        self, restricted_vault_zone: Zone
    ) -> None:
        """Requirement C & I: Separate Evidence records without field stuffing."""
        fence_engine = FenceEngine()
        dwell_engine = DwellEngine(default_max_dwell_s=30.0, default_std_dwell_s=10.0)
        night_engine = NightMovementEngine(min_confidence=0.80)

        subject_ref = "subject_beta_42"
        t0_ns = 1_000_000_000

        # Generate fence event
        fence_ev = fence_engine.check_subject(
            subject_ref=subject_ref,
            bbox=BoundingBox(x1=100, y1=100, x2=200, y2=200),
            camera_id="cam-01",
            timestamp_ns=t0_ns,
            source_resolution=(1000, 1000),
            zones=[restricted_vault_zone],
            confidence=0.96,
        )[0]
        fence_payload = fence_engine.build_evidence_payload(fence_ev)

        # Generate dwell event
        dwell_engine.record_zone_presence(
            subject_ref=subject_ref,
            zone_id="zone_vault",
            camera_id="cam-01",
            timestamp_ns=t0_ns,
            confidence=0.94,
            zone=restricted_vault_zone,
        )
        dwell_ev = dwell_engine.record_zone_presence(
            subject_ref=subject_ref,
            zone_id="zone_vault",
            camera_id="cam-01",
            timestamp_ns=t0_ns + 90_000_000_000,
            confidence=0.94,
            zone=restricted_vault_zone,
        )
        assert dwell_ev is not None
        dwell_payload = dwell_engine.build_evidence_payload(dwell_ev)

        # Generate night event
        night_ev = night_engine.evaluate(
            subject_ref=subject_ref,
            zone_id="zone_vault",
            camera_id="cam-01",
            timestamp_ns=t0_ns + 5_000_000_000,
            lighting_condition=LightingCondition.NIGHT_DARK,
            associated_event_type="RESTRICTED_ZONE_INTRUSION",
            event_confidence=0.91,
        )
        assert night_ev is not None
        night_payload = night_engine.build_evidence_payload(night_ev)

        # Create distinct Evidence records
        evidence_1 = Evidence(
            evidence_id="evd_fence_01",
            source_store="event_store",
            record_type="RESTRICTED_ZONE_INTRUSION",
            record_id="rec_fence_01",
            timestamp_ns=t0_ns,
            camera_id="cam-01",
            global_id=subject_ref,
            explanation=fence_ev.explanation,
            payload=fence_payload,
        )

        evidence_2 = Evidence(
            evidence_id="evd_dwell_01",
            source_store="event_store",
            record_type="LOITERING_DETECTED",
            record_id="rec_dwell_01",
            timestamp_ns=t0_ns + 90_000_000_000,
            camera_id="cam-01",
            global_id=subject_ref,
            explanation=dwell_ev.explanation,
            payload=dwell_payload,
        )

        evidence_3 = Evidence(
            evidence_id="evd_night_01",
            source_store="event_store",
            record_type="NIGHT_MOVEMENT",
            record_id="rec_night_01",
            timestamp_ns=t0_ns + 5_000_000_000,
            camera_id="cam-01",
            global_id=subject_ref,
            explanation=night_ev.explanation,
            payload=night_payload,
        )

        # Requirement I: Verify no cross-field contamination
        assert "zone_dwell_sigma" not in evidence_1.payload
        assert "lighting_condition" not in evidence_1.payload
        assert evidence_1.payload["is_restricted_zone"] is True

        assert "is_restricted_zone" not in evidence_2.payload
        assert "lighting_condition" not in evidence_2.payload
        assert "zone_dwell_sigma" in evidence_2.payload

        assert "is_restricted_zone" not in evidence_3.payload
        assert "zone_dwell_sigma" not in evidence_3.payload
        assert evidence_3.payload["lighting_condition"] == "night_dark"

        # Unique IDs
        assert len({evidence_1.evidence_id, evidence_2.evidence_id, evidence_3.evidence_id}) == 3


class TestSuspiciousActivityCoOccurrence:
    """Proves Requirements E, F, G, and multiple signal combinations."""

    def test_combination_restricted_zone_and_loitering(
        self, restricted_vault_zone: Zone
    ) -> None:
        """Combination 1: RESTRICTED_ZONE_INTRUSION + LOITERING_DETECTED -> SUSPICIOUS_ACTIVITY."""
        fence_engine = FenceEngine()
        dwell_engine = DwellEngine(default_max_dwell_s=30.0, default_std_dwell_s=10.0)
        hypo_generator = HypothesisGenerator()

        subject_ref = "subject_gamma_01"
        t0_ns = 1_000_000_000
        t1_ns = t0_ns + 100_000_000_000

        fence_ev = fence_engine.check_subject(
            subject_ref=subject_ref,
            bbox=BoundingBox(x1=150, y1=150, x2=250, y2=250),
            camera_id="cam-01",
            timestamp_ns=t0_ns,
            source_resolution=(1000, 1000),
            zones=[restricted_vault_zone],
            confidence=0.95,
        )[0]

        dwell_engine.record_zone_presence(
            subject_ref=subject_ref,
            zone_id="zone_vault",
            camera_id="cam-01",
            timestamp_ns=t0_ns,
            confidence=0.93,
            zone=restricted_vault_zone,
        )
        dwell_ev = dwell_engine.record_zone_presence(
            subject_ref=subject_ref,
            zone_id="zone_vault",
            camera_id="cam-01",
            timestamp_ns=t1_ns,
            confidence=0.93,
            zone=restricted_vault_zone,
        )
        assert dwell_ev is not None

        ev1 = Evidence(
            evidence_id="ev_f1",
            source_store="event_store",
            record_type="RESTRICTED_ZONE_INTRUSION",
            record_id="rec_f1",
            timestamp_ns=t0_ns,
            camera_id="cam-01",
            global_id=subject_ref,
            payload=fence_engine.build_evidence_payload(fence_ev),
        )

        ev2 = Evidence(
            evidence_id="ev_d1",
            source_store="event_store",
            record_type="LOITERING_DETECTED",
            record_id="rec_d1",
            timestamp_ns=t1_ns,
            camera_id="cam-01",
            global_id=subject_ref,
            payload=dwell_engine.build_evidence_payload(dwell_ev),
        )

        trees = hypo_generator.generate_trees(
            evidence_items=[ev1, ev2],
            window_start_ns=t0_ns,
            window_end_ns=t1_ns + 1_000_000,
        )

        assert len(trees) >= 1
        primary_hyp = trees[0].root_node.hypothesis

        # Requirement F: Resulting hypothesis is specifically SUSPICIOUS_ACTIVITY
        assert primary_hyp.hypothesis_type == "SUSPICIOUS_ACTIVITY"
        assert primary_hyp.primary_subject_ref == subject_ref

        # Requirement C & E: Evidence IDs link to both independent items
        assert set(primary_hyp.evidence_ids) == {"ev_f1", "ev_d1"}

        # Requirement G: Explanation identifies contributing independent signals
        exp = primary_hyp.explanation
        assert "RESTRICTED_ZONE_INTRUSION" in exp
        assert "LOITERING_DETECTED" in exp
        assert subject_ref in exp

        # Rule 8 non-causal compliance
        for term in PROHIBITED_TERMS:
            assert term not in exp.lower()

        # Child nodes at depth 2 represent the contributing signals
        children = trees[0].root_node.children
        assert len(children) == 2
        child_types = {c.hypothesis.hypothesis_type for c in children}
        assert child_types == {
            "RESTRICTED_ZONE_INTRUSION_signal",
            "LOITERING_DETECTED_signal",
        }

    def test_combination_restricted_zone_and_night_movement(
        self, restricted_vault_zone: Zone
    ) -> None:
        """Combination 2: RESTRICTED_ZONE_INTRUSION + NIGHT_MOVEMENT -> SUSPICIOUS_ACTIVITY."""
        fence_engine = FenceEngine()
        night_engine = NightMovementEngine(min_confidence=0.80)
        hypo_generator = HypothesisGenerator()

        subject_ref = "subject_night_infiltrator"
        t0_ns = 5_000_000_000

        fence_ev = fence_engine.check_subject(
            subject_ref=subject_ref,
            bbox=BoundingBox(x1=50, y1=50, x2=150, y2=150),
            camera_id="cam-01",
            timestamp_ns=t0_ns,
            source_resolution=(1000, 1000),
            zones=[restricted_vault_zone],
            confidence=0.96,
        )[0]

        night_ev = night_engine.evaluate(
            subject_ref=subject_ref,
            zone_id="zone_vault",
            camera_id="cam-01",
            timestamp_ns=t0_ns + 1_000_000_000,
            lighting_condition=LightingCondition.NIGHT_DARK,
            associated_event_type="RESTRICTED_ZONE_INTRUSION",
            event_confidence=0.88,
        )
        assert night_ev is not None

        ev_fence = Evidence(
            evidence_id="ev_fn_1",
            source_store="event_store",
            record_type="RESTRICTED_ZONE_INTRUSION",
            record_id="rec_fn_1",
            timestamp_ns=t0_ns,
            camera_id="cam-01",
            global_id=subject_ref,
            payload=fence_engine.build_evidence_payload(fence_ev),
        )

        ev_night = Evidence(
            evidence_id="ev_nn_1",
            source_store="event_store",
            record_type="NIGHT_MOVEMENT",
            record_id="rec_nn_1",
            timestamp_ns=t0_ns + 1_000_000_000,
            camera_id="cam-01",
            global_id=subject_ref,
            payload=night_engine.build_evidence_payload(night_ev),
        )

        trees = hypo_generator.generate_trees(
            evidence_items=[ev_fence, ev_night],
            window_start_ns=t0_ns,
            window_end_ns=t0_ns + 10_000_000_000,
        )

        assert len(trees) >= 1
        assert trees[0].root_node.hypothesis.hypothesis_type == "SUSPICIOUS_ACTIVITY"
        assert set(trees[0].root_node.hypothesis.evidence_ids) == {"ev_fn_1", "ev_nn_1"}
        assert "RESTRICTED_ZONE_INTRUSION" in trees[0].root_node.hypothesis.explanation
        assert "NIGHT_MOVEMENT" in trees[0].root_node.hypothesis.explanation

    def test_combination_loitering_and_night_movement(
        self, restricted_vault_zone: Zone
    ) -> None:
        """Combination 3: LOITERING_DETECTED + NIGHT_MOVEMENT -> SUSPICIOUS_ACTIVITY."""
        dwell_engine = DwellEngine(default_max_dwell_s=30.0, default_std_dwell_s=10.0)
        night_engine = NightMovementEngine(min_confidence=0.80)
        hypo_generator = HypothesisGenerator()

        subject_ref = "subject_night_loiterer"
        t0_ns = 2_000_000_000
        t1_ns = t0_ns + 80_000_000_000

        dwell_engine.record_zone_presence(
            subject_ref=subject_ref,
            zone_id="zone_vault",
            camera_id="cam-01",
            timestamp_ns=t0_ns,
            confidence=0.90,
            zone=restricted_vault_zone,
        )
        dwell_ev = dwell_engine.record_zone_presence(
            subject_ref=subject_ref,
            zone_id="zone_vault",
            camera_id="cam-01",
            timestamp_ns=t1_ns,
            confidence=0.90,
            zone=restricted_vault_zone,
        )
        assert dwell_ev is not None

        night_ev = night_engine.evaluate(
            subject_ref=subject_ref,
            zone_id="zone_vault",
            camera_id="cam-01",
            timestamp_ns=t1_ns,
            lighting_condition=LightingCondition.NIGHT_LIT,
            associated_event_type="LOITERING_DETECTED",
            event_confidence=0.85,
        )
        assert night_ev is not None

        ev_dwell = Evidence(
            evidence_id="ev_ld_1",
            source_store="event_store",
            record_type="LOITERING_DETECTED",
            record_id="rec_ld_1",
            timestamp_ns=t1_ns,
            camera_id="cam-01",
            global_id=subject_ref,
            payload=dwell_engine.build_evidence_payload(dwell_ev),
        )

        ev_night = Evidence(
            evidence_id="ev_ln_1",
            source_store="event_store",
            record_type="NIGHT_MOVEMENT",
            record_id="rec_ln_1",
            timestamp_ns=t1_ns,
            camera_id="cam-01",
            global_id=subject_ref,
            payload=night_engine.build_evidence_payload(night_ev),
        )

        trees = hypo_generator.generate_trees(
            evidence_items=[ev_dwell, ev_night],
            window_start_ns=t0_ns,
            window_end_ns=t1_ns + 10_000_000,
        )

        assert len(trees) >= 1
        assert trees[0].root_node.hypothesis.hypothesis_type == "SUSPICIOUS_ACTIVITY"
        assert set(trees[0].root_node.hypothesis.evidence_ids) == {"ev_ld_1", "ev_ln_1"}
        assert "LOITERING_DETECTED" in trees[0].root_node.hypothesis.explanation
        assert "NIGHT_MOVEMENT" in trees[0].root_node.hypothesis.explanation


class TestNegativeControlCases:
    """Proves Requirement H: Co-occurrence guard enforcement."""

    def test_single_event_restricted_zone_only_no_suspicious_activity(
        self, restricted_vault_zone: Zone
    ) -> None:
        """Control 1: ONLY RESTRICTED_ZONE_INTRUSION -> SUSPICIOUS_ACTIVITY is NOT produced."""
        fence_engine = FenceEngine()
        hypo_generator = HypothesisGenerator()
        subject_ref = "subject_control_fence"

        fence_ev = fence_engine.check_subject(
            subject_ref=subject_ref,
            bbox=BoundingBox(x1=100, y1=100, x2=200, y2=200),
            camera_id="cam-01",
            timestamp_ns=1_000_000_000,
            source_resolution=(1000, 1000),
            zones=[restricted_vault_zone],
            confidence=0.95,
        )[0]

        ev_fence = Evidence(
            evidence_id="ev_ctrl_f1",
            source_store="event_store",
            record_type="RESTRICTED_ZONE_INTRUSION",
            record_id="rec_ctrl_f1",
            timestamp_ns=1_000_000_000,
            camera_id="cam-01",
            global_id=subject_ref,
            payload=fence_engine.build_evidence_payload(fence_ev),
        )

        trees = hypo_generator.generate_trees(
            evidence_items=[ev_fence],
            window_start_ns=1_000_000_000,
            window_end_ns=2_000_000_000,
        )

        hypo_types = [t.root_node.hypothesis.hypothesis_type for t in trees]
        assert "SUSPICIOUS_ACTIVITY" not in hypo_types
        assert "RESTRICTED_ZONE_INTRUSION" in hypo_types

    def test_single_event_loitering_only_no_suspicious_activity(
        self, restricted_vault_zone: Zone
    ) -> None:
        """Control 2: ONLY LOITERING_DETECTED -> SUSPICIOUS_ACTIVITY is NOT produced."""
        dwell_engine = DwellEngine(default_max_dwell_s=30.0, default_std_dwell_s=10.0)
        hypo_generator = HypothesisGenerator()
        subject_ref = "subject_control_dwell"

        dwell_engine.record_zone_presence(
            subject_ref=subject_ref,
            zone_id="zone_vault",
            camera_id="cam-01",
            timestamp_ns=1_000_000_000,
            confidence=0.92,
            zone=restricted_vault_zone,
        )
        dwell_ev = dwell_engine.record_zone_presence(
            subject_ref=subject_ref,
            zone_id="zone_vault",
            camera_id="cam-01",
            timestamp_ns=100_000_000_000,
            confidence=0.92,
            zone=restricted_vault_zone,
        )
        assert dwell_ev is not None

        ev_dwell = Evidence(
            evidence_id="ev_ctrl_d1",
            source_store="event_store",
            record_type="LOITERING_DETECTED",
            record_id="rec_ctrl_d1",
            timestamp_ns=100_000_000_000,
            camera_id="cam-01",
            global_id=subject_ref,
            payload=dwell_engine.build_evidence_payload(dwell_ev),
        )

        trees = hypo_generator.generate_trees(
            evidence_items=[ev_dwell],
            window_start_ns=1_000_000_000,
            window_end_ns=150_000_000_000,
        )

        hypo_types = [t.root_node.hypothesis.hypothesis_type for t in trees]
        assert "SUSPICIOUS_ACTIVITY" not in hypo_types
        assert "LOITERING_DETECTED" in hypo_types

    def test_single_event_night_movement_only_no_suspicious_activity(self) -> None:
        """Control 3: ONLY NIGHT_MOVEMENT -> SUSPICIOUS_ACTIVITY is NOT produced."""
        night_engine = NightMovementEngine(min_confidence=0.80)
        hypo_generator = HypothesisGenerator()
        subject_ref = "subject_control_night"

        night_ev = night_engine.evaluate(
            subject_ref=subject_ref,
            zone_id="zone_transit",
            camera_id="cam-01",
            timestamp_ns=1_000_000_000,
            lighting_condition=LightingCondition.NIGHT_DARK,
            associated_event_type="VIRTUAL_FENCE_CROSSED",
            event_confidence=0.85,
        )
        assert night_ev is not None

        ev_night = Evidence(
            evidence_id="ev_ctrl_n1",
            source_store="event_store",
            record_type="NIGHT_MOVEMENT",
            record_id="rec_ctrl_n1",
            timestamp_ns=1_000_000_000,
            camera_id="cam-01",
            global_id=subject_ref,
            payload=night_engine.build_evidence_payload(night_ev),
        )

        trees = hypo_generator.generate_trees(
            evidence_items=[ev_night],
            window_start_ns=1_000_000_000,
            window_end_ns=2_000_000_000,
        )

        hypo_types = [t.root_node.hypothesis.hypothesis_type for t in trees]
        assert "SUSPICIOUS_ACTIVITY" not in hypo_types
        assert "NIGHT_MOVEMENT" in hypo_types

    def test_different_subjects_no_cross_subject_leakage(
        self, restricted_vault_zone: Zone
    ) -> None:
        """Control 4: Events belong to different subjects -> NO SUSPICIOUS_ACTIVITY produced."""
        fence_engine = FenceEngine()
        dwell_engine = DwellEngine(default_max_dwell_s=30.0, default_std_dwell_s=10.0)
        hypo_generator = HypothesisGenerator()

        subject_a = "subject_alice"
        subject_b = "subject_bob"

        # Subject A intrudes restricted zone
        fence_ev = fence_engine.check_subject(
            subject_ref=subject_a,
            bbox=BoundingBox(x1=100, y1=100, x2=200, y2=200),
            camera_id="cam-01",
            timestamp_ns=1_000_000_000,
            source_resolution=(1000, 1000),
            zones=[restricted_vault_zone],
            confidence=0.95,
        )[0]
        ev_a = Evidence(
            evidence_id="ev_subj_a",
            source_store="event_store",
            record_type="RESTRICTED_ZONE_INTRUSION",
            record_id="rec_a",
            timestamp_ns=1_000_000_000,
            camera_id="cam-01",
            global_id=subject_a,
            payload=fence_engine.build_evidence_payload(fence_ev),
        )

        # Subject B loiters elsewhere
        dwell_engine.record_zone_presence(
            subject_ref=subject_b,
            zone_id="zone_vault",
            camera_id="cam-01",
            timestamp_ns=1_000_000_000,
            confidence=0.92,
            zone=restricted_vault_zone,
        )
        dwell_ev = dwell_engine.record_zone_presence(
            subject_ref=subject_b,
            zone_id="zone_vault",
            camera_id="cam-01",
            timestamp_ns=100_000_000_000,
            confidence=0.92,
            zone=restricted_vault_zone,
        )
        assert dwell_ev is not None
        ev_b = Evidence(
            evidence_id="ev_subj_b",
            source_store="event_store",
            record_type="LOITERING_DETECTED",
            record_id="rec_b",
            timestamp_ns=100_000_000_000,
            camera_id="cam-01",
            global_id=subject_b,
            payload=dwell_engine.build_evidence_payload(dwell_ev),
        )

        trees = hypo_generator.generate_trees(
            evidence_items=[ev_a, ev_b],
            window_start_ns=1_000_000_000,
            window_end_ns=150_000_000_000,
        )

        # Neither subject has >= 2 signals, so SUSPICIOUS_ACTIVITY must NOT be emitted
        hypo_types = [t.root_node.hypothesis.hypothesis_type for t in trees]
        assert "SUSPICIOUS_ACTIVITY" not in hypo_types
        assert len(trees) == 2


class TestEvaluatorCrossEvidenceIntegration:
    """Verifies that SituationalRiskEvaluator correctly evaluates distributed evidence."""

    def test_evaluator_fires_critical_on_distributed_evidence_items(
        self, restricted_vault_zone: Zone
    ) -> None:
        """Proves that SituationalRiskEvaluator evaluates multi-factor rules across separate evidence items."""
        evaluator = SituationalRiskEvaluator()
        fence_engine = FenceEngine()
        dwell_engine = DwellEngine(default_max_dwell_s=30.0, default_std_dwell_s=10.0)

        subject_ref = "subject_distributed_crit"
        now_ns = 1_000_000_000_000
        t0_ns = now_ns - 100_000_000_000
        t1_ns = now_ns

        # 1. Fence event: provides is_restricted_zone=True
        fence_ev = fence_engine.check_subject(
            subject_ref=subject_ref,
            bbox=BoundingBox(x1=100, y1=100, x2=200, y2=200),
            camera_id="cam-01",
            timestamp_ns=t0_ns,
            source_resolution=(1000, 1000),
            zones=[restricted_vault_zone],
            confidence=0.96,
        )[0]
        ev_fence = Evidence(
            evidence_id="ev_dist_f1",
            source_store="event_store",
            record_type="RESTRICTED_ZONE_INTRUSION",
            record_id="rec_dist_f1",
            timestamp_ns=t0_ns,
            camera_id="cam-01",
            global_id=subject_ref,
            payload=fence_engine.build_evidence_payload(fence_ev),
        )

        # 2. Dwell event: provides zone_dwell_sigma > 5.0
        dwell_engine.record_zone_presence(
            subject_ref=subject_ref,
            zone_id="zone_vault",
            camera_id="cam-01",
            timestamp_ns=t0_ns,
            confidence=0.95,
            zone=restricted_vault_zone,
        )
        dwell_ev = dwell_engine.record_zone_presence(
            subject_ref=subject_ref,
            zone_id="zone_vault",
            camera_id="cam-01",
            timestamp_ns=t1_ns,
            confidence=0.95,
            zone=restricted_vault_zone,
        )
        assert dwell_ev is not None
        assert dwell_ev.zone_dwell_sigma > 5.0
        ev_dwell = Evidence(
            evidence_id="ev_dist_d1",
            source_store="event_store",
            record_type="LOITERING_DETECTED",
            record_id="rec_dist_d1",
            timestamp_ns=t1_ns,
            camera_id="cam-01",
            global_id=subject_ref,
            payload=dwell_engine.build_evidence_payload(dwell_ev),
        )

        # 3. Trajectory anomaly event: provides trajectory_anomaly_sigma > 3.5
        ev_traj = Evidence(
            evidence_id="ev_dist_t1",
            source_store="event_store",
            record_type="TRAJECTORY_ANOMALY",
            record_id="rec_dist_t1",
            timestamp_ns=t1_ns - 10_000_000_000,
            camera_id="cam-01",
            global_id=subject_ref,
            payload={
                "trajectory_anomaly_sigma": 4.1,
                "confidence": 0.94,
                "subject_ref": subject_ref,
            },
        )

        # Evaluate all 3 distinct items together
        risk_signal = evaluator.evaluate(
            evidence_items=[ev_fence, ev_dwell, ev_traj],
            system_mode=SystemMode.OPERATIONAL_MODE,
            window_start_ns=t0_ns,
            window_end_ns=t1_ns,
        )

        assert risk_signal.risk_level == "CRITICAL"
        assert risk_signal.risk_score == 1.00
        assert risk_signal.suppressed is False

        # All 3 factors present in contributing factors
        factors = set(risk_signal.contributing_factors)
        assert "restricted_zone_condition" in factors
        assert "zone_dwell_gt_5.0sigma" in factors
        assert "trajectory_anomaly_gt_3.5sigma" in factors

        # All 3 evidence IDs preserved
        assert set(risk_signal.evidence_ids) == {
            "ev_dist_f1",
            "ev_dist_d1",
            "ev_dist_t1",
        }
